# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CreditHourEntry(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, value: float=None, grant_to: int=None, grant_by: int=None, grant_for: int=None, grant_note: str=None, grade: int=None, application_id: int=None):  # noqa: E501
        """CreditHourEntry - a model defined in Swagger

        :param value: The value of this CreditHourEntry.  # noqa: E501
        :type value: float
        :param grant_to: The grant_to of this CreditHourEntry.  # noqa: E501
        :type grant_to: int
        :param grant_by: The grant_by of this CreditHourEntry.  # noqa: E501
        :type grant_by: int
        :param grant_for: The grant_for of this CreditHourEntry.  # noqa: E501
        :type grant_for: int
        :param grant_note: The grant_note of this CreditHourEntry.  # noqa: E501
        :type grant_note: str
        :param grade: The grade of this CreditHourEntry.  # noqa: E501
        :type grade: int
        :param application_id: The application_id of this CreditHourEntry.  # noqa: E501
        :type application_id: int
        """
        self.swagger_types = {
            'value': float,
            'grant_to': int,
            'grant_by': int,
            'grant_for': int,
            'grant_note': str,
            'grade': int,
            'application_id': int
        }

        self.attribute_map = {
            'value': 'value',
            'grant_to': 'grantTo',
            'grant_by': 'grantBy',
            'grant_for': 'grantFor',
            'grant_note': 'grantNote',
            'grade': 'grade',
            'application_id': 'applicationId'
        }

        self._value = value
        self._grant_to = grant_to
        self._grant_by = grant_by
        self._grant_for = grant_for
        self._grant_note = grant_note
        self._grade = grade
        self._application_id = application_id

    @classmethod
    def from_dict(cls, dikt) -> 'CreditHourEntry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreditHourEntry of this CreditHourEntry.  # noqa: E501
        :rtype: CreditHourEntry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> float:
        """Gets the value of this CreditHourEntry.

        学时授予值(按分钟记)  # noqa: E501

        :return: The value of this CreditHourEntry.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this CreditHourEntry.

        学时授予值(按分钟记)  # noqa: E501

        :param value: The value of this CreditHourEntry.
        :type value: float
        """

        self._value = value

    @property
    def grant_to(self) -> int:
        """Gets the grant_to of this CreditHourEntry.

        学时获得者ID  # noqa: E501

        :return: The grant_to of this CreditHourEntry.
        :rtype: int
        """
        return self._grant_to

    @grant_to.setter
    def grant_to(self, grant_to: int):
        """Sets the grant_to of this CreditHourEntry.

        学时获得者ID  # noqa: E501

        :param grant_to: The grant_to of this CreditHourEntry.
        :type grant_to: int
        """

        self._grant_to = grant_to

    @property
    def grant_by(self) -> int:
        """Gets the grant_by of this CreditHourEntry.

        学时申请者ID(若是课程学时则为课程导师申请)  # noqa: E501

        :return: The grant_by of this CreditHourEntry.
        :rtype: int
        """
        return self._grant_by

    @grant_by.setter
    def grant_by(self, grant_by: int):
        """Sets the grant_by of this CreditHourEntry.

        学时申请者ID(若是课程学时则为课程导师申请)  # noqa: E501

        :param grant_by: The grant_by of this CreditHourEntry.
        :type grant_by: int
        """

        self._grant_by = grant_by

    @property
    def grant_for(self) -> int:
        """Gets the grant_for of this CreditHourEntry.

        学时相关项目ID(若无相关项目，则为0)  # noqa: E501

        :return: The grant_for of this CreditHourEntry.
        :rtype: int
        """
        return self._grant_for

    @grant_for.setter
    def grant_for(self, grant_for: int):
        """Sets the grant_for of this CreditHourEntry.

        学时相关项目ID(若无相关项目，则为0)  # noqa: E501

        :param grant_for: The grant_for of this CreditHourEntry.
        :type grant_for: int
        """

        self._grant_for = grant_for

    @property
    def grant_note(self) -> str:
        """Gets the grant_note of this CreditHourEntry.

        学时授予备注  # noqa: E501

        :return: The grant_note of this CreditHourEntry.
        :rtype: str
        """
        return self._grant_note

    @grant_note.setter
    def grant_note(self, grant_note: str):
        """Sets the grant_note of this CreditHourEntry.

        学时授予备注  # noqa: E501

        :param grant_note: The grant_note of this CreditHourEntry.
        :type grant_note: str
        """

        self._grant_note = grant_note

    @property
    def grade(self) -> int:
        """Gets the grade of this CreditHourEntry.

        学时相关绩点（若不属于绩点学时，则为-1）  # noqa: E501

        :return: The grade of this CreditHourEntry.
        :rtype: int
        """
        return self._grade

    @grade.setter
    def grade(self, grade: int):
        """Sets the grade of this CreditHourEntry.

        学时相关绩点（若不属于绩点学时，则为-1）  # noqa: E501

        :param grade: The grade of this CreditHourEntry.
        :type grade: int
        """

        self._grade = grade

    @property
    def application_id(self) -> int:
        """Gets the application_id of this CreditHourEntry.

        学时相关申请(若不存在申请环节，则为0)  # noqa: E501

        :return: The application_id of this CreditHourEntry.
        :rtype: int
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id: int):
        """Sets the application_id of this CreditHourEntry.

        学时相关申请(若不存在申请环节，则为0)  # noqa: E501

        :param application_id: The application_id of this CreditHourEntry.
        :type application_id: int
        """

        self._application_id = application_id
