# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LearnerMedicalInfoPreviousDiagnosis(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name_of_diagnosis: str=None, hospital_of_diagnosis: str=None):  # noqa: E501
        """LearnerMedicalInfoPreviousDiagnosis - a model defined in Swagger

        :param name_of_diagnosis: The name_of_diagnosis of this LearnerMedicalInfoPreviousDiagnosis.  # noqa: E501
        :type name_of_diagnosis: str
        :param hospital_of_diagnosis: The hospital_of_diagnosis of this LearnerMedicalInfoPreviousDiagnosis.  # noqa: E501
        :type hospital_of_diagnosis: str
        """
        self.swagger_types = {
            'name_of_diagnosis': str,
            'hospital_of_diagnosis': str
        }

        self.attribute_map = {
            'name_of_diagnosis': 'nameOfDiagnosis',
            'hospital_of_diagnosis': 'hospitalOfDiagnosis'
        }

        self._name_of_diagnosis = name_of_diagnosis
        self._hospital_of_diagnosis = hospital_of_diagnosis

    @classmethod
    def from_dict(cls, dikt) -> 'LearnerMedicalInfoPreviousDiagnosis':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Learner_medicalInfo_previousDiagnosis of this LearnerMedicalInfoPreviousDiagnosis.  # noqa: E501
        :rtype: LearnerMedicalInfoPreviousDiagnosis
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name_of_diagnosis(self) -> str:
        """Gets the name_of_diagnosis of this LearnerMedicalInfoPreviousDiagnosis.

        疾病名称  # noqa: E501

        :return: The name_of_diagnosis of this LearnerMedicalInfoPreviousDiagnosis.
        :rtype: str
        """
        return self._name_of_diagnosis

    @name_of_diagnosis.setter
    def name_of_diagnosis(self, name_of_diagnosis: str):
        """Sets the name_of_diagnosis of this LearnerMedicalInfoPreviousDiagnosis.

        疾病名称  # noqa: E501

        :param name_of_diagnosis: The name_of_diagnosis of this LearnerMedicalInfoPreviousDiagnosis.
        :type name_of_diagnosis: str
        """

        self._name_of_diagnosis = name_of_diagnosis

    @property
    def hospital_of_diagnosis(self) -> str:
        """Gets the hospital_of_diagnosis of this LearnerMedicalInfoPreviousDiagnosis.

        诊断医院  # noqa: E501

        :return: The hospital_of_diagnosis of this LearnerMedicalInfoPreviousDiagnosis.
        :rtype: str
        """
        return self._hospital_of_diagnosis

    @hospital_of_diagnosis.setter
    def hospital_of_diagnosis(self, hospital_of_diagnosis: str):
        """Sets the hospital_of_diagnosis of this LearnerMedicalInfoPreviousDiagnosis.

        诊断医院  # noqa: E501

        :param hospital_of_diagnosis: The hospital_of_diagnosis of this LearnerMedicalInfoPreviousDiagnosis.
        :type hospital_of_diagnosis: str
        """

        self._hospital_of_diagnosis = hospital_of_diagnosis
