# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LearnerContactInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, phone_number: str=None, we_chat: str=None, qq: str=None, mail_address: str=None, email: str=None):  # noqa: E501
        """LearnerContactInfo - a model defined in Swagger

        :param phone_number: The phone_number of this LearnerContactInfo.  # noqa: E501
        :type phone_number: str
        :param we_chat: The we_chat of this LearnerContactInfo.  # noqa: E501
        :type we_chat: str
        :param qq: The qq of this LearnerContactInfo.  # noqa: E501
        :type qq: str
        :param mail_address: The mail_address of this LearnerContactInfo.  # noqa: E501
        :type mail_address: str
        :param email: The email of this LearnerContactInfo.  # noqa: E501
        :type email: str
        """
        self.swagger_types = {
            'phone_number': str,
            'we_chat': str,
            'qq': str,
            'mail_address': str,
            'email': str
        }

        self.attribute_map = {
            'phone_number': 'phoneNumber',
            'we_chat': 'weChat',
            'qq': 'QQ',
            'mail_address': 'mailAddress',
            'email': 'email'
        }

        self._phone_number = phone_number
        self._we_chat = we_chat
        self._qq = qq
        self._mail_address = mail_address
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'LearnerContactInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Learner_contactInfo of this LearnerContactInfo.  # noqa: E501
        :rtype: LearnerContactInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def phone_number(self) -> str:
        """Gets the phone_number of this LearnerContactInfo.

        电话号码  # noqa: E501

        :return: The phone_number of this LearnerContactInfo.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: str):
        """Sets the phone_number of this LearnerContactInfo.

        电话号码  # noqa: E501

        :param phone_number: The phone_number of this LearnerContactInfo.
        :type phone_number: str
        """

        self._phone_number = phone_number

    @property
    def we_chat(self) -> str:
        """Gets the we_chat of this LearnerContactInfo.

        微信  # noqa: E501

        :return: The we_chat of this LearnerContactInfo.
        :rtype: str
        """
        return self._we_chat

    @we_chat.setter
    def we_chat(self, we_chat: str):
        """Sets the we_chat of this LearnerContactInfo.

        微信  # noqa: E501

        :param we_chat: The we_chat of this LearnerContactInfo.
        :type we_chat: str
        """

        self._we_chat = we_chat

    @property
    def qq(self) -> str:
        """Gets the qq of this LearnerContactInfo.

        QQ  # noqa: E501

        :return: The qq of this LearnerContactInfo.
        :rtype: str
        """
        return self._qq

    @qq.setter
    def qq(self, qq: str):
        """Sets the qq of this LearnerContactInfo.

        QQ  # noqa: E501

        :param qq: The qq of this LearnerContactInfo.
        :type qq: str
        """

        self._qq = qq

    @property
    def mail_address(self) -> str:
        """Gets the mail_address of this LearnerContactInfo.

        收件地址（用以寄送书面文件）  # noqa: E501

        :return: The mail_address of this LearnerContactInfo.
        :rtype: str
        """
        return self._mail_address

    @mail_address.setter
    def mail_address(self, mail_address: str):
        """Sets the mail_address of this LearnerContactInfo.

        收件地址（用以寄送书面文件）  # noqa: E501

        :param mail_address: The mail_address of this LearnerContactInfo.
        :type mail_address: str
        """

        self._mail_address = mail_address

    @property
    def email(self) -> str:
        """Gets the email of this LearnerContactInfo.

        电子邮箱  # noqa: E501

        :return: The email of this LearnerContactInfo.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this LearnerContactInfo.

        电子邮箱  # noqa: E501

        :param email: The email of this LearnerContactInfo.
        :type email: str
        """

        self._email = email
