# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LearnerMedicalInfoFoodAlergy(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, lactose_intolerance: bool=None, egg_allergy: bool=None, fish_allergy: bool=None, shell_allergy: bool=None, peanut_allergy: bool=None, soy_bean_allergy: bool=None, nut_allergy: bool=None, wheat_allergy: bool=None, other_food_allergy: List[str]=None):  # noqa: E501
        """LearnerMedicalInfoFoodAlergy - a model defined in Swagger

        :param lactose_intolerance: The lactose_intolerance of this LearnerMedicalInfoFoodAlergy.  # noqa: E501
        :type lactose_intolerance: bool
        :param egg_allergy: The egg_allergy of this LearnerMedicalInfoFoodAlergy.  # noqa: E501
        :type egg_allergy: bool
        :param fish_allergy: The fish_allergy of this LearnerMedicalInfoFoodAlergy.  # noqa: E501
        :type fish_allergy: bool
        :param shell_allergy: The shell_allergy of this LearnerMedicalInfoFoodAlergy.  # noqa: E501
        :type shell_allergy: bool
        :param peanut_allergy: The peanut_allergy of this LearnerMedicalInfoFoodAlergy.  # noqa: E501
        :type peanut_allergy: bool
        :param soy_bean_allergy: The soy_bean_allergy of this LearnerMedicalInfoFoodAlergy.  # noqa: E501
        :type soy_bean_allergy: bool
        :param nut_allergy: The nut_allergy of this LearnerMedicalInfoFoodAlergy.  # noqa: E501
        :type nut_allergy: bool
        :param wheat_allergy: The wheat_allergy of this LearnerMedicalInfoFoodAlergy.  # noqa: E501
        :type wheat_allergy: bool
        :param other_food_allergy: The other_food_allergy of this LearnerMedicalInfoFoodAlergy.  # noqa: E501
        :type other_food_allergy: List[str]
        """
        self.swagger_types = {
            'lactose_intolerance': bool,
            'egg_allergy': bool,
            'fish_allergy': bool,
            'shell_allergy': bool,
            'peanut_allergy': bool,
            'soy_bean_allergy': bool,
            'nut_allergy': bool,
            'wheat_allergy': bool,
            'other_food_allergy': List[str]
        }

        self.attribute_map = {
            'lactose_intolerance': 'lactoseIntolerance',
            'egg_allergy': 'eggAllergy',
            'fish_allergy': 'fishAllergy',
            'shell_allergy': 'shellAllergy',
            'peanut_allergy': 'peanutAllergy',
            'soy_bean_allergy': 'soyBeanAllergy',
            'nut_allergy': 'nutAllergy',
            'wheat_allergy': 'wheatAllergy',
            'other_food_allergy': 'otherFoodAllergy'
        }

        self._lactose_intolerance = lactose_intolerance
        self._egg_allergy = egg_allergy
        self._fish_allergy = fish_allergy
        self._shell_allergy = shell_allergy
        self._peanut_allergy = peanut_allergy
        self._soy_bean_allergy = soy_bean_allergy
        self._nut_allergy = nut_allergy
        self._wheat_allergy = wheat_allergy
        self._other_food_allergy = other_food_allergy

    @classmethod
    def from_dict(cls, dikt) -> 'LearnerMedicalInfoFoodAlergy':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Learner_medicalInfo_foodAlergy of this LearnerMedicalInfoFoodAlergy.  # noqa: E501
        :rtype: LearnerMedicalInfoFoodAlergy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lactose_intolerance(self) -> bool:
        """Gets the lactose_intolerance of this LearnerMedicalInfoFoodAlergy.

        奶类过敏（乳糖不耐受）  # noqa: E501

        :return: The lactose_intolerance of this LearnerMedicalInfoFoodAlergy.
        :rtype: bool
        """
        return self._lactose_intolerance

    @lactose_intolerance.setter
    def lactose_intolerance(self, lactose_intolerance: bool):
        """Sets the lactose_intolerance of this LearnerMedicalInfoFoodAlergy.

        奶类过敏（乳糖不耐受）  # noqa: E501

        :param lactose_intolerance: The lactose_intolerance of this LearnerMedicalInfoFoodAlergy.
        :type lactose_intolerance: bool
        """

        self._lactose_intolerance = lactose_intolerance

    @property
    def egg_allergy(self) -> bool:
        """Gets the egg_allergy of this LearnerMedicalInfoFoodAlergy.

        禽蛋类过敏  # noqa: E501

        :return: The egg_allergy of this LearnerMedicalInfoFoodAlergy.
        :rtype: bool
        """
        return self._egg_allergy

    @egg_allergy.setter
    def egg_allergy(self, egg_allergy: bool):
        """Sets the egg_allergy of this LearnerMedicalInfoFoodAlergy.

        禽蛋类过敏  # noqa: E501

        :param egg_allergy: The egg_allergy of this LearnerMedicalInfoFoodAlergy.
        :type egg_allergy: bool
        """

        self._egg_allergy = egg_allergy

    @property
    def fish_allergy(self) -> bool:
        """Gets the fish_allergy of this LearnerMedicalInfoFoodAlergy.

        鱼类过敏  # noqa: E501

        :return: The fish_allergy of this LearnerMedicalInfoFoodAlergy.
        :rtype: bool
        """
        return self._fish_allergy

    @fish_allergy.setter
    def fish_allergy(self, fish_allergy: bool):
        """Sets the fish_allergy of this LearnerMedicalInfoFoodAlergy.

        鱼类过敏  # noqa: E501

        :param fish_allergy: The fish_allergy of this LearnerMedicalInfoFoodAlergy.
        :type fish_allergy: bool
        """

        self._fish_allergy = fish_allergy

    @property
    def shell_allergy(self) -> bool:
        """Gets the shell_allergy of this LearnerMedicalInfoFoodAlergy.

        甲壳类（虾蟹、贝类水产等）  # noqa: E501

        :return: The shell_allergy of this LearnerMedicalInfoFoodAlergy.
        :rtype: bool
        """
        return self._shell_allergy

    @shell_allergy.setter
    def shell_allergy(self, shell_allergy: bool):
        """Sets the shell_allergy of this LearnerMedicalInfoFoodAlergy.

        甲壳类（虾蟹、贝类水产等）  # noqa: E501

        :param shell_allergy: The shell_allergy of this LearnerMedicalInfoFoodAlergy.
        :type shell_allergy: bool
        """

        self._shell_allergy = shell_allergy

    @property
    def peanut_allergy(self) -> bool:
        """Gets the peanut_allergy of this LearnerMedicalInfoFoodAlergy.

        花生过敏  # noqa: E501

        :return: The peanut_allergy of this LearnerMedicalInfoFoodAlergy.
        :rtype: bool
        """
        return self._peanut_allergy

    @peanut_allergy.setter
    def peanut_allergy(self, peanut_allergy: bool):
        """Sets the peanut_allergy of this LearnerMedicalInfoFoodAlergy.

        花生过敏  # noqa: E501

        :param peanut_allergy: The peanut_allergy of this LearnerMedicalInfoFoodAlergy.
        :type peanut_allergy: bool
        """

        self._peanut_allergy = peanut_allergy

    @property
    def soy_bean_allergy(self) -> bool:
        """Gets the soy_bean_allergy of this LearnerMedicalInfoFoodAlergy.

        大豆过敏  # noqa: E501

        :return: The soy_bean_allergy of this LearnerMedicalInfoFoodAlergy.
        :rtype: bool
        """
        return self._soy_bean_allergy

    @soy_bean_allergy.setter
    def soy_bean_allergy(self, soy_bean_allergy: bool):
        """Sets the soy_bean_allergy of this LearnerMedicalInfoFoodAlergy.

        大豆过敏  # noqa: E501

        :param soy_bean_allergy: The soy_bean_allergy of this LearnerMedicalInfoFoodAlergy.
        :type soy_bean_allergy: bool
        """

        self._soy_bean_allergy = soy_bean_allergy

    @property
    def nut_allergy(self) -> bool:
        """Gets the nut_allergy of this LearnerMedicalInfoFoodAlergy.

        坚果类过敏  # noqa: E501

        :return: The nut_allergy of this LearnerMedicalInfoFoodAlergy.
        :rtype: bool
        """
        return self._nut_allergy

    @nut_allergy.setter
    def nut_allergy(self, nut_allergy: bool):
        """Sets the nut_allergy of this LearnerMedicalInfoFoodAlergy.

        坚果类过敏  # noqa: E501

        :param nut_allergy: The nut_allergy of this LearnerMedicalInfoFoodAlergy.
        :type nut_allergy: bool
        """

        self._nut_allergy = nut_allergy

    @property
    def wheat_allergy(self) -> bool:
        """Gets the wheat_allergy of this LearnerMedicalInfoFoodAlergy.

        小麦过敏  # noqa: E501

        :return: The wheat_allergy of this LearnerMedicalInfoFoodAlergy.
        :rtype: bool
        """
        return self._wheat_allergy

    @wheat_allergy.setter
    def wheat_allergy(self, wheat_allergy: bool):
        """Sets the wheat_allergy of this LearnerMedicalInfoFoodAlergy.

        小麦过敏  # noqa: E501

        :param wheat_allergy: The wheat_allergy of this LearnerMedicalInfoFoodAlergy.
        :type wheat_allergy: bool
        """

        self._wheat_allergy = wheat_allergy

    @property
    def other_food_allergy(self) -> List[str]:
        """Gets the other_food_allergy of this LearnerMedicalInfoFoodAlergy.

        其他食物过敏  # noqa: E501

        :return: The other_food_allergy of this LearnerMedicalInfoFoodAlergy.
        :rtype: List[str]
        """
        return self._other_food_allergy

    @other_food_allergy.setter
    def other_food_allergy(self, other_food_allergy: List[str]):
        """Sets the other_food_allergy of this LearnerMedicalInfoFoodAlergy.

        其他食物过敏  # noqa: E501

        :param other_food_allergy: The other_food_allergy of this LearnerMedicalInfoFoodAlergy.
        :type other_food_allergy: List[str]
        """

        self._other_food_allergy = other_food_allergy
