# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LearnerMedicalInfoRegularMedication(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name_of_medication: str=None, instruction_of_medication: str=None):  # noqa: E501
        """LearnerMedicalInfoRegularMedication - a model defined in Swagger

        :param name_of_medication: The name_of_medication of this LearnerMedicalInfoRegularMedication.  # noqa: E501
        :type name_of_medication: str
        :param instruction_of_medication: The instruction_of_medication of this LearnerMedicalInfoRegularMedication.  # noqa: E501
        :type instruction_of_medication: str
        """
        self.swagger_types = {
            'name_of_medication': str,
            'instruction_of_medication': str
        }

        self.attribute_map = {
            'name_of_medication': 'nameOfMedication',
            'instruction_of_medication': 'instructionOfMedication'
        }

        self._name_of_medication = name_of_medication
        self._instruction_of_medication = instruction_of_medication

    @classmethod
    def from_dict(cls, dikt) -> 'LearnerMedicalInfoRegularMedication':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Learner_medicalInfo_regularMedication of this LearnerMedicalInfoRegularMedication.  # noqa: E501
        :rtype: LearnerMedicalInfoRegularMedication
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name_of_medication(self) -> str:
        """Gets the name_of_medication of this LearnerMedicalInfoRegularMedication.

        药品名  # noqa: E501

        :return: The name_of_medication of this LearnerMedicalInfoRegularMedication.
        :rtype: str
        """
        return self._name_of_medication

    @name_of_medication.setter
    def name_of_medication(self, name_of_medication: str):
        """Sets the name_of_medication of this LearnerMedicalInfoRegularMedication.

        药品名  # noqa: E501

        :param name_of_medication: The name_of_medication of this LearnerMedicalInfoRegularMedication.
        :type name_of_medication: str
        """

        self._name_of_medication = name_of_medication

    @property
    def instruction_of_medication(self) -> str:
        """Gets the instruction_of_medication of this LearnerMedicalInfoRegularMedication.

        用药医嘱  # noqa: E501

        :return: The instruction_of_medication of this LearnerMedicalInfoRegularMedication.
        :rtype: str
        """
        return self._instruction_of_medication

    @instruction_of_medication.setter
    def instruction_of_medication(self, instruction_of_medication: str):
        """Sets the instruction_of_medication of this LearnerMedicalInfoRegularMedication.

        用药医嘱  # noqa: E501

        :param instruction_of_medication: The instruction_of_medication of this LearnerMedicalInfoRegularMedication.
        :type instruction_of_medication: str
        """

        self._instruction_of_medication = instruction_of_medication
