# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LearnerEmergentContact(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, number: str=None):  # noqa: E501
        """LearnerEmergentContact - a model defined in Swagger

        :param name: The name of this LearnerEmergentContact.  # noqa: E501
        :type name: str
        :param number: The number of this LearnerEmergentContact.  # noqa: E501
        :type number: str
        """
        self.swagger_types = {
            'name': str,
            'number': str
        }

        self.attribute_map = {
            'name': 'name',
            'number': 'number'
        }

        self._name = name
        self._number = number

    @classmethod
    def from_dict(cls, dikt) -> 'LearnerEmergentContact':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Learner_emergentContact of this LearnerEmergentContact.  # noqa: E501
        :rtype: LearnerEmergentContact
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this LearnerEmergentContact.

        紧急联系人姓名  # noqa: E501

        :return: The name of this LearnerEmergentContact.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this LearnerEmergentContact.

        紧急联系人姓名  # noqa: E501

        :param name: The name of this LearnerEmergentContact.
        :type name: str
        """

        self._name = name

    @property
    def number(self) -> str:
        """Gets the number of this LearnerEmergentContact.

        紧急联系人电话  # noqa: E501

        :return: The number of this LearnerEmergentContact.
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number: str):
        """Sets the number of this LearnerEmergentContact.

        紧急联系人电话  # noqa: E501

        :param number: The number of this LearnerEmergentContact.
        :type number: str
        """

        self._number = number
