# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectProjectApprovalInfoApprovalCommitteeOfAcademics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, result: str=None, advice: str=None):  # noqa: E501
        """ProjectProjectApprovalInfoApprovalCommitteeOfAcademics - a model defined in Swagger

        :param result: The result of this ProjectProjectApprovalInfoApprovalCommitteeOfAcademics.  # noqa: E501
        :type result: str
        :param advice: The advice of this ProjectProjectApprovalInfoApprovalCommitteeOfAcademics.  # noqa: E501
        :type advice: str
        """
        self.swagger_types = {
            'result': str,
            'advice': str
        }

        self.attribute_map = {
            'result': 'result',
            'advice': 'advice'
        }

        self._result = result
        self._advice = advice

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectProjectApprovalInfoApprovalCommitteeOfAcademics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Project_projectApprovalInfo_ApprovalCommitteeOfAcademics of this ProjectProjectApprovalInfoApprovalCommitteeOfAcademics.  # noqa: E501
        :rtype: ProjectProjectApprovalInfoApprovalCommitteeOfAcademics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> str:
        """Gets the result of this ProjectProjectApprovalInfoApprovalCommitteeOfAcademics.

        学术委员会审核结果  # noqa: E501

        :return: The result of this ProjectProjectApprovalInfoApprovalCommitteeOfAcademics.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result: str):
        """Sets the result of this ProjectProjectApprovalInfoApprovalCommitteeOfAcademics.

        学术委员会审核结果  # noqa: E501

        :param result: The result of this ProjectProjectApprovalInfoApprovalCommitteeOfAcademics.
        :type result: str
        """

        self._result = result

    @property
    def advice(self) -> str:
        """Gets the advice of this ProjectProjectApprovalInfoApprovalCommitteeOfAcademics.

        学术委员会审核建议  # noqa: E501

        :return: The advice of this ProjectProjectApprovalInfoApprovalCommitteeOfAcademics.
        :rtype: str
        """
        return self._advice

    @advice.setter
    def advice(self, advice: str):
        """Sets the advice of this ProjectProjectApprovalInfoApprovalCommitteeOfAcademics.

        学术委员会审核建议  # noqa: E501

        :param advice: The advice of this ProjectProjectApprovalInfoApprovalCommitteeOfAcademics.
        :type advice: str
        """

        self._advice = advice
