# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectConclusionInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, self_evaluation: str=None, mentor_evaluation: str=None):  # noqa: E501
        """ProjectConclusionInfo - a model defined in Swagger

        :param self_evaluation: The self_evaluation of this ProjectConclusionInfo.  # noqa: E501
        :type self_evaluation: str
        :param mentor_evaluation: The mentor_evaluation of this ProjectConclusionInfo.  # noqa: E501
        :type mentor_evaluation: str
        """
        self.swagger_types = {
            'self_evaluation': str,
            'mentor_evaluation': str
        }

        self.attribute_map = {
            'self_evaluation': 'selfEvaluation',
            'mentor_evaluation': 'mentorEvaluation'
        }

        self._self_evaluation = self_evaluation
        self._mentor_evaluation = mentor_evaluation

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectConclusionInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Project_conclusionInfo of this ProjectConclusionInfo.  # noqa: E501
        :rtype: ProjectConclusionInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def self_evaluation(self) -> str:
        """Gets the self_evaluation of this ProjectConclusionInfo.

        项目负责人结项自评  # noqa: E501

        :return: The self_evaluation of this ProjectConclusionInfo.
        :rtype: str
        """
        return self._self_evaluation

    @self_evaluation.setter
    def self_evaluation(self, self_evaluation: str):
        """Sets the self_evaluation of this ProjectConclusionInfo.

        项目负责人结项自评  # noqa: E501

        :param self_evaluation: The self_evaluation of this ProjectConclusionInfo.
        :type self_evaluation: str
        """

        self._self_evaluation = self_evaluation

    @property
    def mentor_evaluation(self) -> str:
        """Gets the mentor_evaluation of this ProjectConclusionInfo.

        导师结项评语  # noqa: E501

        :return: The mentor_evaluation of this ProjectConclusionInfo.
        :rtype: str
        """
        return self._mentor_evaluation

    @mentor_evaluation.setter
    def mentor_evaluation(self, mentor_evaluation: str):
        """Sets the mentor_evaluation of this ProjectConclusionInfo.

        导师结项评语  # noqa: E501

        :param mentor_evaluation: The mentor_evaluation of this ProjectConclusionInfo.
        :type mentor_evaluation: str
        """

        self._mentor_evaluation = mentor_evaluation
