# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.project_project_approval_info_approval_mentor import ProjectProjectApprovalInfoApprovalMentor  # noqa: F401,E501
from swagger_server import util


class ProjectProjectApprovalInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, approval_mentor: ProjectProjectApprovalInfoApprovalMentor=None):  # noqa: E501
        """ProjectProjectApprovalInfo - a model defined in Swagger

        :param approval_mentor: The approval_mentor of this ProjectProjectApprovalInfo.  # noqa: E501
        :type approval_mentor: ProjectProjectApprovalInfoApprovalMentor
        """
        self.swagger_types = {
            'approval_mentor': ProjectProjectApprovalInfoApprovalMentor
        }

        self.attribute_map = {
            'approval_mentor': 'approvalMentor'
        }

        self._approval_mentor = approval_mentor

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectProjectApprovalInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Project_projectApprovalInfo of this ProjectProjectApprovalInfo.  # noqa: E501
        :rtype: ProjectProjectApprovalInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def approval_mentor(self) -> ProjectProjectApprovalInfoApprovalMentor:
        """Gets the approval_mentor of this ProjectProjectApprovalInfo.


        :return: The approval_mentor of this ProjectProjectApprovalInfo.
        :rtype: ProjectProjectApprovalInfoApprovalMentor
        """
        return self._approval_mentor

    @approval_mentor.setter
    def approval_mentor(self, approval_mentor: ProjectProjectApprovalInfoApprovalMentor):
        """Sets the approval_mentor of this ProjectProjectApprovalInfo.


        :param approval_mentor: The approval_mentor of this ProjectProjectApprovalInfo.
        :type approval_mentor: ProjectProjectApprovalInfoApprovalMentor
        """

        self._approval_mentor = approval_mentor
